baseurl = "https://byzantine-blog-craddock.netlify.com/"
title = "Byantine Blog"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'A history blog on the Byzantine Empire, the successor state to the Roman Empire'
  logo = "fa-diamond"



[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/aecraddock/Adamblog"

[languages]
[languages.en]
languageName = "English"
weight = 1


title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
